
Categorical Encoding: Label Encoding & One Hot Encoding

In [1]:
# Categorical encoding adalah proses konversi nilai kategorical menjadi nilai numerik
# Hal ini penting karena banyak algoritma machine learning hanya dapat bekerja dengan data numerik
# Beberapa teknik encoding yang umum digunakan antara lain:
# 1. One-Hot Encoding: Mengubah setiap kategori menjadi kolom biner (0 atau 1)
# 2. Label Encoding: Mengubah setiap kategori menjadi angka integer
# 3. Ordinal Encoding: Mengubah kategori menjadi angka integer berdasarkan urutan tertentu (TIDAK DIBAHAS DISINI, INI CATATAN AI)

In [2]:
#Pada Label Encoding, setiap kategori pada suatu feature akan diurutkan secara alfabet
#dan direpresentasikan dengan sebuah nilai integer

#Dataset
import pandas as pd
df = pd.DataFrame({
    'country': ['India', 'US', 'Japan', 'US', 'Japan'],
    'age': [44, 34, 46, 35, 23],
    'salary': [72000, 65000, 98000, 45000, 34000]
})

df

  country  age  salary
0   India   44   72000
1      US   34   65000
2   Japan   46   98000
3      US   35   45000
4   Japan   23   34000

Label Encoding Pada Scikit Learn

In [3]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['country'] = label_encoder.fit_transform(df['country'])
df

   country  age  salary
0        0   44   72000
1        2   34   65000
2        1   46   98000
3        2   35   45000
4        1   23   34000

In [4]:

label_encoder.classes_

array(['India', 'Japan', 'US'], dtype=object)

In [5]:
#label encoding mengurutkan secara alfabet dan memberikan nilai integer berdasarkan urutan tersebut
#India -> 0, Japan -> 1, US -> 2
#India<Japan<US (Ga boleh kek gini harusnya)

One Hot Encoding

In [6]:

#Pada One Hot Encoding, setiap kategori pada suatu feature akan diubah menjadi sebuah kolom baru yang berisi nilai biner (0 atau 1)
#atau setiap kategori akan diurutkan secara alfabet dan direpresentasikan sebagai sekumpulan bits.

#Dataset
df = pd.DataFrame({
    'country': ['India', 'US', 'Japan', 'US', 'Japan'],
    'age': [44, 34, 46, 35, 23],
    'salary': [72000, 65000, 98000, 45000, 34000]
})

df

  country  age  salary
0   India   44   72000
1      US   34   65000
2   Japan   46   98000
3      US   35   45000
4   Japan   23   34000

In [7]:

X = df['country'].values.reshape(-1, 1)
X

array([['India'],
       ['US'],
       ['Japan'],
       ['US'],
       ['Japan']], dtype=object)

In [8]:

from sklearn.preprocessing import OneHotEncoder

onehot_encoder = OneHotEncoder()
X = onehot_encoder.fit_transform(X).toarray()
X

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [9]:

onehot_encoder.categories_

[array(['India', 'Japan', 'US'], dtype=object)]

In [10]:
df_onehot = pd.DataFrame(X, columns=[str(i) for i in range(X.shape[1])])
df_onehot

     0    1    2
0  1.0  0.0  0.0
1  0.0  0.0  1.0
2  0.0  1.0  0.0
3  0.0  0.0  1.0
4  0.0  1.0  0.0

In [11]:
df = pd.concat([df_onehot, df], axis=1)
df

     0    1    2 country  age  salary
0  1.0  0.0  0.0   India   44   72000
1  0.0  0.0  1.0      US   34   65000
2  0.0  1.0  0.0   Japan   46   98000
3  0.0  0.0  1.0      US   35   45000
4  0.0  1.0  0.0   Japan   23   34000

In [12]:

df = df.drop(['country'], axis=1)
df

     0    1    2  age  salary
0  1.0  0.0  0.0   44   72000
1  0.0  0.0  1.0   34   65000
2  0.0  1.0  0.0   46   98000
3  0.0  0.0  1.0   35   45000
4  0.0  1.0  0.0   23   34000

In [13]:
#Label Encoding vs One-Hot Encoding

#Kita Menerapkan ONE HOT ENCODING bila:
#1. Nilai kategorikal adalah nominal (tidak memiliki urutan atau hierarki)
#2. Jumlah kategori relatif kecil (biasanya kurang dari 10)
#3. Kita ingin menghindari asumsi urutan yang tidak benar pada data

#Kita Menerapkan LABEL ENCODING bila:
#1. Nilai kategorikal adalah ordinal (memiliki urutan atau hierarki)
#2. Jumlah kategori relatif besar (biasanya lebih dari 10)
#3. Kita ingin mempertahankan informasi urutan dalam data